"""empty message

Revision ID: 046627445cda
Revises: 3824607ba1cf
Create Date: 2025-11-07 19:59:06.101737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046627445cda'
down_revision = '3824607ba1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('import_color')

    # ### end Alembic commands ###
