"""remove days_to_learn from priority_settings

Revision ID: 3824607ba1cf
Revises: 391fb2296a48
Create Date: 2025-11-02 19:04:41.547634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3824607ba1cf'
down_revision = '391fb2296a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('priority_setting', schema=None) as batch_op:
        batch_op.drop_column('days_to_learn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('priority_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_to_learn', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
