"""add dark_mode to settings

Revision ID: 587d380f1221
Revises: 046627445cda
Create Date: 2025-11-08 23:37:11.099393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587d380f1221'
down_revision = '046627445cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dark_mode', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('dark_mode')

    # ### end Alembic commands ###
